### ISSUE TITLE
Can not run, encounter error ' AttributeError: 'bool' object has no attribute '__module__'. Did you mean: '__mod__'?'

### ISSUE THREAD

**Issue by Learningm** [Roblox/FlashTex#7]
Following the tutorial and run inference with depth control net and encounter the following problem.

```
Traceback (most recent call last):
  File "/repo/FlashTex/generate_texture.py", line 358, in <module>
    main(args, progress_callback=progress_callback)
  File "/repo/FlashTex/generate_texture.py", line 342, in main
    output_images, diffusion_noise_init = generate_initial_character_sheet(args, mesh_dict, view_strings)
  File "/repo/FlashTex/generate_texture.py", line 238, in generate_initial_character_sheet
    return generate_avatar_image(
  File "/repo/FlashTex/generate_texture.py", line 205, in generate_avatar_image
    avatar_image_generator = AvatarImageGenerator(args, preloaded_models=None, device=args.device)
  File "/repo/FlashTex/models/avatar_image_generator.py", line 68, in __init__
    self.diffusion_model = self.create_diffusion_model(model_id=args.model_id, use_img2img=use_img2img, pretrained_dir=pretrained_dir)
  File "/repo/FlashTex/models/avatar_image_generator.py", line 82, in create_diffusion_model
    model = Depth2Image_Diffusers(**model_args)
  File "/repo/FlashTex/models/depth2image_diffusers.py", line 38, in __init__
    self.pipe = pipe_class.from_pretrained(
  File "/home/envs/flashtex/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1196, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "/repo/FlashTex/ldm/pipeline_controlnet_img2img.py", line 69, in __init__
    super().__init__(
  File "/home/envs/flashtex/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py", line 187, in __init__
    self.register_modules(
  File "/home/envs/flashtex/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 519, in register_modules
    library = not_compiled_module.__module__.split(".")[0]
AttributeError: 'bool' object has no attribute '__module__'. Did you mean: '__mod__'?

```
Tried some workaround but still can not fix the problem.
https://github.com/huggingface/diffusers/issues/6324#issuecomment-2090012436

Tried downgrading huggingface_hub version to avoid another 'cache_download' import problem.

Current version tried：
diffusers: 0.21.1 / 0.21.3 / 0.25.0 / 0.30.2
huggingface_hub: 0.25.0(avoid cache_download import problem)

But the problem 'AttributeError' mentioned above still not solved.

Could you give me some advices? Thank you.

**Comment by Learningm** [comment]
Found out some previous changed not necessary.
depth2image_diffusers.py pass the safety_checker=False on line 42, back to 'None' solved the problem.
